server:
  port: 8081
spring:
  # 应用名
  application:
    name: RabbitMQ_Provider_DirectExchange
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 开启消息确认(消息生产者发送消息到rabbitmq服务器后, 会被告知是否发送成功)
    publisher-confirms: true
    publisher-returns: true